spring:
  profiles:
    active: eureka7001

---
server:
  port: 7001

spring:
  profiles: eureka7001
  application:
    name: springcloud-config-eureka-7001

# Eureka 配置
eureka:
  instance:
    hostname: eureka7001 # Eureka 服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向 eureka 注册中心注册自己（服务端不需要）
    fetch-registry: false # false 表示自己为注册中心
    service-url:    # 监控页面
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---

server:
  port: 7002

spring:
  profiles: eureka7002
  application:
    name: springcloud-config-eureka-7002

# Eureka 配置
eureka:
  instance:
    hostname: eureka7002 # Eureka 服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向 eureka 注册中心注册自己（服务端不需要）
    fetch-registry: false # false 表示自己为注册中心
    service-url:    # 监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
---

server:
  port: 7003

spring:
  profiles: eureka7003
  application:
    name: springcloud-config-eureka-7003

# Eureka 配置
eureka:
  instance:
    hostname: eureka7003 # Eureka 服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向 eureka 注册中心注册自己（服务端不需要）
    fetch-registry: false # false 表示自己为注册中心
    service-url:    # 监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
